from __future__ import annotations
import typing
__all__: list[str] = ['AES', 'CHACHA20', 'ITZData', 'IsLinkedData', 'MSGPACK', 'PacketParseException', 'PingData', 'QueueAbortException', 'SocketReadException', 'TZBot', 'TZFlags', 'TZRequest', 'TZResponse', 'TimezoneFromIPData', 'TimezoneFromUUIDData', 'TimezoneFromUserIDData', 'UUIDFromUserIDData', 'UpdateTimezoneData', 'UserIDUUIDLinkData', 'UserIdFromUUIDData']
class ITZData:
    def __init__(self) -> None:
        ...
    def get_byte_representation(self) -> int:
        ...
    def is_api_key_needed(self) -> bool:
        ...
    def to_json(self) -> dict:
        ...
class IsLinkedData(ITZData):
    def __init__(self, uuid: str) -> None:
        ...
    def get_byte_representation(self) -> int:
        ...
    def is_api_key_needed(self) -> bool:
        ...
    def to_json(self) -> dict:
        ...
class PingData(ITZData):
    def __init__(self) -> None:
        ...
    def get_byte_representation(self) -> int:
        ...
    def is_api_key_needed(self) -> bool:
        ...
    def to_json(self) -> dict:
        ...
class QueueAbortException(Exception):
    pass

class PacketParseException(Exception):
    pass
class SocketReadException(Exception):
    pass
class TZFlags:
    """
    Members:
    
      AES
    
      CHACHA20
    
      MSGPACK
    """
    AES: typing.ClassVar[TZFlags]  # value = <TZFlags.AES: 1>
    CHACHA20: typing.ClassVar[TZFlags]  # value = <TZFlags.CHACHA20: 2>
    MSGPACK: typing.ClassVar[TZFlags]  # value = <TZFlags.MSGPACK: 8>
    __members__: typing.ClassVar[dict[str, TZFlags]]  # value = {'AES': <TZFlags.AES: 1>, 'CHACHA20': <TZFlags.CHACHA20: 2>, 'MSGPACK': <TZFlags.MSGPACK: 8>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __ge__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __gt__(self, other: typing.Any) -> bool:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __le__(self, other: typing.Any) -> bool:
        ...
    def __lt__(self, other: typing.Any) -> bool:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...

class TZRequest:
    def __init__(self, data: ITZData) -> None:
        ...
    def get_request_type(self) -> int:
        ...
    def to_json(self) -> dict:
        ...
class TZResponse:
    def to_json(self) -> dict:
        ...
    def get_code(self) -> int:
        ...
    def get_response_int(self) -> int | None:
        ...
    def get_response_str(self) -> str | None:
        ...
    def is_successful(self) -> bool:
        ...

class TZBot:
    def __init__(self, ip_address: str, port: typing.SupportsInt, api_key: str, encryption_key: str) -> None:
        ...
    async def make_request(self, request: TZRequest) -> TZResponse:
        ...
    def set_flags(self, *args) -> None:
        ...
class TimezoneFromIPData(ITZData):
    def __init__(self, ip_address: str) -> None:
        ...
    def get_byte_representation(self) -> int:
        ...
    def is_api_key_needed(self) -> bool:
        ...
    def to_json(self) -> dict:
        ...
class TimezoneFromUUIDData(ITZData):
    def __init__(self, uuid: str) -> None:
        ...
    def get_byte_representation(self) -> int:
        ...
    def is_api_key_needed(self) -> bool:
        ...
    def to_json(self) -> dict:
        ...
class TimezoneFromUserIDData(ITZData):
    def __init__(self, user_id: typing.SupportsInt) -> None:
        ...
    def get_byte_representation(self) -> int:
        ...
    def is_api_key_needed(self) -> bool:
        ...
    def to_json(self) -> dict:
        ...
class UUIDFromUserIDData(ITZData):
    def __init__(self, user_id: typing.SupportsInt) -> None:
        ...
    def get_byte_representation(self) -> int:
        ...
    def is_api_key_needed(self) -> bool:
        ...
    def to_json(self) -> dict:
        ...
class UpdateTimezoneData(ITZData):
    def __init__(self, uuid: str, timezone: str) -> None:
        ...
    def get_byte_representation(self) -> int:
        ...
    def is_api_key_needed(self) -> bool:
        ...
    def to_json(self) -> dict:
        ...
class UserIDUUIDLinkData(ITZData):
    def __init__(self, user_id: typing.SupportsInt, uuid: str) -> None:
        ...
    def get_byte_representation(self) -> int:
        ...
    def is_api_key_needed(self) -> bool:
        ...
    def to_json(self) -> dict:
        ...
class UserIdFromUUIDData(ITZData):
    def __init__(self, uuid: str) -> None:
        ...
    def get_byte_representation(self) -> int:
        ...
    def is_api_key_needed(self) -> bool:
        ...
    def to_json(self) -> dict:
        ...
AES: TZFlags  # value = <TZFlags.AES: 1>
CHACHA20: TZFlags  # value = <TZFlags.CHACHA20: 2>
MSGPACK: TZFlags  # value = <TZFlags.MSGPACK: 8>
